#! /bin/sh
USAGE="Usage: `basename $0` [-h] [-u username] [-p password] [-t tenant]"

OKAPI="http://shared-index.reshare-dev.indexdata.com:9130"
TENANT="diku"
UN="diku_admin"
PW="admin"

if [ -f .okapirc ]; then
  . .okapirc
elif [ -f $HOME/.okapirc ]; then
  . $HOME/.okapirc
fi

# Parse command line options.
while getopts hupt: OPT; do
  case "$OPT" in
    h)
      echo $USAGE
      exit 0
      ;;
    u)
      UN=$OPTARG
      ;;
    p)
      PW=$OPTARG
      ;;
    t)
      TENANT=$OPTARG
      ;;
    \?)
      # getopts issues an error message
      echo $USAGE >&2
      exit 1
      ;;
  esac
done

# Remove the options we parsed above.
shift `expr $OPTIND - 1`
echo $OKAPI $TENANT
AUTH_TOKEN=$(curl -sSL -D - -X POST -H 'accept: application/json' -H 'Content-type: application/json' \
    -H "X-Okapi-Tenant: $TENANT" --connect-timeout 5 --max-time 30 -d "{ \"username\":\"${UN}\", \"password\": \"${PW}\" }" \
    "${OKAPI}/authn/login" | grep -Fi x-okapi-token | sed 's/.*: *//' | xargs)
echo $AUTH_TOKEN
exit 0
