
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: reshare
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: 'postgres:14'
          ports:
            - containerPort: 5432
          env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: folio-db-connect
                key: DB_PASSWORD
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: folio-db-connect
                key: DB_USERNAME
          # - name: POSTGRES_DATABASE
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: folio-db-connect
                key: DB_DATABASE
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgres-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: reshare
  labels:
    app: postgres
spec:
  type: "NodePort"
  selector:
    app: "postgres"
  ports:
    - name: postgres
      port: 5432
      nodePort: 30543
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-claim
  namespace: reshare
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi