#%RAML 1.0

title: ResourceSharing API
baseUri: https://github.com/openlibraryenvironment/mod-rs
version: v1

documentation:
  - title: mod-rs API
    content: This documents the API calls that can be made to query and manage resource sharing requests

types:
  note: !include patronRequest.json
