name: k8s-deploy-latest

env:
  K8S_NAMESPACE: 'reshare'
  K8S_DEPLOYMENT: 'mod-rs-latest'

on:
  push:

jobs: 
  k8s-deploy-latest:

    runs-on: ubuntu-latest
    steps: 
      - name: Deactivate mod-rs
        run: /usr/bin/python3 ./.github/scripts/disable.py

      - name: Deploy latest to K8s
        uses: actions-hub/kubectl@v1.21.2
        env: 
          KUBE_CONFIG: ${{ secrets.RESHARE_DEV_SA_KUBECONFIG }}
        with:
          args:
            -n ${{ env.K8S_NAMESPACE }} rollout restart deployment ${{ env.K8S_DEPLOYMENT }}
