name: deploy

on:
  workflow_dispatch:

env:
  K8S_NAMESPACE: 'reshare'
  K8S_DEPLOYMENT: 'mod-rs-slnp'

jobs:
  deploy:

    runs-on: ubuntu-latest
    steps:
      - name: checkout module
        uses: actions/checkout@v3

      - name: Deploy latest to K8s
        uses: actions-hub/kubectl@v1.21.2
        env:
          KUBE_CONFIG: ${{ secrets.RESHARE_DEV_SA_KUBECONFIG }}
        with:
          args:
            -n ${{ env.K8S_NAMESPACE }} rollout restart deployment ${{ env.K8S_DEPLOYMENT }}
