name: Publish ISO18626 client

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Build with Gradle
      run: |
          cd iso18626-client
          ./gradlew build
      
    - name: Publish to reposolite
      run: |
        secret="${{ secrets.REPOSOLITE_USERNAME }}"
        length=0
        while [ -n "$secret" ]; do
          secret="${secret#?}"
          (( length++ ))
        done
        echo "Username length: $length"
        secret_value=${{ secrets.REPOSOLITE_USERNAME }}
        echo "First 5 characters of secret: ${secret_value:0:5}"
        cd iso18626-client
        ./gradlew publish
      env:
        REPOSOLITE_USERNAME: ${{ secrets.REPOSOLITE_USERNAME }}
        REPOSOLITE_PASSWORD: ${{ secrets.REPOSOLITE_PASSWORD }}
